### ISSUE TITLE
This user doesn't have access to ZeroTier

### ISSUE THREAD

**Issue by JelloEmperor** [aaron777collins/ZeroTier-GUI-Arch#2]
Trying to launch the GUI gives me "This user doesn't have access to ZeroTier" error. I've tried uninstalling and reinstalling, and deleting the zerotier-one folder between to no avail. running the command: `sudo -S ./zerotier-cli -D/home/{user}/.zerotier-one listnetworks` returns the error ` ./zerotier-cli: missing port and zerotier-one.port not found in /home/deck/.zerotier-one`

**Comment by aaron777collins** [comment]
According to [this post](https://stackoverflow.com/questions/68494575/zerotier-cli-command-giving-error-missing-port-and-zerotier-one-port-not-found) it looks like either the service isn't running or the port is already in use.
Just to check, have you installed zerotier via any other methods (rwfus, etc.) and have a duplicate service? Or maybe a service running on on the same port (9993)?
You could try checking the startup failure reason with:
```journalctl --user -u zerotier-one.service```

Once you've run the following command, please share the output logs.
From there, we can figure out a solution :)

**Comment by aaron777collins** [comment]
Another option is going to ~/.zerotier-one and modifying the zerotier-one.port file to use 9994 or some other unused port. This is probably the fastest solution but skips over the main issue that there's a program using the port in the first place. If you are confident this is your only zerotier instance, feel free to just use this solution instead.

**Comment by JelloEmperor** [comment]
> According to [this post](https://stackoverflow.com/questions/68494575/zerotier-cli-command-giving-error-missing-port-and-zerotier-one-port-not-found) it looks like either the service isn't running or the port is already in use. Just to check, have you installed zerotier via any other methods (rwfus, etc.) and have a duplicate service? Or maybe a service running on on the same port (9993)? You could try checking the startup failure reason with: `journalctl --user -u zerotier-one.service`
> 
> Once you've run the following command, please share the output logs. From there, we can figure out a solution :)

So I had actually used rwfus in the past to install, but I had thought I removed it. Let me look into this a little deeper.

**Comment by JelloEmperor** [comment]
`Aug 02 12:34:43 steamdeck systemd[1026]: Started zerotier-one.service.
Aug 02 12:34:43 steamdeck sudo[18245]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Aug 02 12:34:43 steamdeck sudo[18245]:     deck : PWD=/home/deck ; USER=root ; COMMAND=/home/deck/.zerotier-one/zerotier-one -U /home/deck/.zerotier-one
Aug 02 12:34:43 steamdeck sudo[18245]: pam_unix(sudo:session): session opened for user root(uid=0) by deck(uid=1000)
Aug 02 12:34:43 steamdeck sudo[18245]: pam_unix(sudo:session): session closed for user root
Aug 02 12:34:43 steamdeck systemd[1026]: zerotier-one.service: Main process exited, code=exited, status=1/FAILURE
Aug 02 12:34:43 steamdeck systemd[1026]: zerotier-one.service: Failed with result 'exit-code'.
Aug 02 12:34:43 steamdeck systemd[1026]: zerotier-one.service: Scheduled restart job, restart counter is at 1.
Aug 02 12:34:43 steamdeck systemd[1026]: Stopped zerotier-one.service.
Aug 02 12:34:43 steamdeck systemd[1026]: Started zerotier-one.service.
Aug 02 12:34:43 steamdeck sudo[18262]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Aug 02 12:34:43 steamdeck sudo[18262]:     deck : PWD=/home/deck ; USER=root ; COMMAND=/home/deck/.zerotier-one/zerotier-one -U /home/deck/.zerotier-one
Aug 02 12:34:43 steamdeck sudo[18262]: pam_unix(sudo:session): session opened for user root(uid=0) by deck(uid=1000)
Aug 02 12:34:44 steamdeck sudo[18262]: pam_unix(sudo:session): session closed for user root
Aug 02 12:34:44 steamdeck systemd[1026]: zerotier-one.service: Main process exited, code=exited, status=1/FAILURE
Aug 02 12:34:44 steamdeck systemd[1026]: zerotier-one.service: Failed with result 'exit-code'.
Aug 02 12:34:44 steamdeck systemd[1026]: zerotier-one.service: Scheduled restart job, restart counter is at 2.
Aug 02 12:34:44 steamdeck systemd[1026]: Stopped zerotier-one.service.
Aug 02 12:34:44 steamdeck systemd[1026]: Started zerotier-one.service.
Aug 02 12:34:44 steamdeck sudo[18272]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Aug 02 12:34:44 steamdeck sudo[18272]:     deck : PWD=/home/deck ; USER=root ; COMMAND=/home/deck/.zerotier-one/zerotier-one -U /home/deck/.zerotier-one
Aug 02 12:34:44 steamdeck sudo[18272]: pam_unix(sudo:session): session opened for user root(uid=0) by deck(uid=1000)
Aug 02 12:34:44 steamdeck sudo[18272]: pam_unix(sudo:session): session closed for user root
Aug 02 12:34:44 steamdeck systemd[1026]: zerotier-one.service: Main process exited, code=exited, status=1/FAILURE
Aug 02 12:34:44 steamdeck systemd[1026]: zerotier-one.service: Failed with result 'exit-code'.
Aug 02 12:34:44 steamdeck systemd[1026]: zerotier-one.service: Scheduled restart job, restart counter is at 3.
Aug 02 12:34:44 steamdeck systemd[1026]: Stopped zerotier-one.service.
Aug 02 12:34:44 steamdeck systemd[1026]: Started zerotier-one.service.
Aug 02 12:34:44 steamdeck sudo[18281]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Aug 02 12:34:44 steamdeck sudo[18281]:     deck : PWD=/home/deck ; USER=root ; COMMAND=/home/deck/.zerotier-one/zerotier-one -U /home/deck/.zerotier-one
Aug 02 12:34:44 steamdeck sudo[18281]: pam_unix(sudo:session): session opened for user root(uid=0) by deck(uid=1000)
Aug 02 12:34:44 steamdeck sudo[18281]: pam_unix(sudo:session): session closed for user root
Aug 02 12:34:44 steamdeck systemd[1026]: zerotier-one.service: Main process exited, code=exited, status=1/FAILURE
Aug 02 12:34:44 steamdeck systemd[1026]: zerotier-one.service: Failed with result 'exit-code'.
Aug 02 12:34:44 steamdeck systemd[1026]: zerotier-one.service: Scheduled restart job, restart counter is at 4.
Aug 02 12:34:44 steamdeck systemd[1026]: Stopped zerotier-one.service.
Aug 02 12:34:44 steamdeck systemd[1026]: Started zerotier-one.service.
Aug 02 12:34:44 steamdeck sudo[18290]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.`

**Comment by aaron777collins** [comment]
Hey would you mind running

`systemctl status zerotier-one.service`

For me? you might need to add sudo in front of it. It should check on the status of your original ZeroTier service (the one you installed with rwfus). If that one is still running, it is likely causing the issue.

**Comment by aaron777collins** [comment]
For reference, I installed the service at the user level so it should be separate.

**Comment by JelloEmperor** [comment]
● zerotier-one.service - ZeroTier One
     Loaded: loaded (/etc/systemd/system/zerotier-one.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-08-01 12:16:35 EDT; 1 day 3h ago
   Main PID: 1081 (zerotier-one)
      Tasks: 5 (limit: 14125)
     Memory: 18.8M
        CPU: 15.238s
     CGroup: /system.slice/zerotier-one.service
             └─1081 /usr/bin/zerotier-one

Aug 01 12:16:35 steamdeck systemd[1]: Started ZeroTier One.
Aug 01 12:16:35 steamdeck zerotier-one[1081]: sendto: Network is unreachable

which is odd because when I try to run `zerotier-cli status` tells me command not found.

**Comment by aaron777collins** [comment]
Yeah you can remove it or atleast disable it. 

`systemctl disable zerotier-one.service`

Should disable it for now and you can remove it fully later.

**Comment by aaron777collins** [comment]
Oh sorry I forgot, you'll need to run the stop command too to stop it.

**Comment by JelloEmperor** [comment]
That worked! Gui has now launched.

**Comment by JelloEmperor** [comment]
Thank you very much, everything seems to be working flawlessly now.

**Comment by aaron777collins** [comment]
You're welcome! Let me know if any other issues arise :)
