### ISSUE TITLE
Always getting Error pop up 

### ISSUE THREAD

**Issue by tistasis** [aaron777collins/ZeroTier-GUI-Arch#3]
After a rebbot from the Steam Deck, trying to open the GUI get a message error that service is not running and after several pop ups I get an Erro window telling "Failed to start zerotier-one.service: Unit zerotier-one.service nor found"

The only way I have been able to "fix" this is moving to trash the zerotier one folder and running all over the GUI again.

Is there a way to fix this problem and GUI works correctly?

**Comment by aaron777collins** [comment]
Hi thanks for opening an issue!

Hmmm that’s odd. Would you happen to know what pop ups came before that? 

Here’s my hypothesis: the program detects issues in running ZeroTier and tries un-installing and re-installing the program, but fails mid way during the re-install. Could you try running the installer again, hitting “uninstall” and do that. Then try re-installing again. I’m curious if maybe some permission issue is hidden behind the scenes.

**Comment by aaron777collins** [comment]
Also if possible, could you take note of which windows popped up and what they said before you got to that error? It will help me debug and fix this.

**Comment by aaron777collins** [comment]
No response for a month. I'll close this for now. Feel free to comment if you'd like and I'll re-open it
