### ISSUE TITLE
When accessing on stable branch, Zerotier-GUI throws errors until crashing/exiting

### ISSUE THREAD

**Issue by OttersMeep** [aaron777collins/ZeroTier-GUI-Arch#5]
When opening Zerotier-GUI off of the beta branch, Zerotier-GUI throws an error of "Zerotier Service not started... starting zerotier service" followed by "Zerotier service started successfully", then looping back around to the first error.

**Comment by OttersMeep** [comment]
After more testing, it looks like this error throws when switching between Steam Deck branches

The solution is just to uninstall and reinstall (or dont switch brances)

**Comment by OttersMeep** [comment]
Going to put in a seperate issue

**Comment by aaron777collins** [comment]
My latest changes should solve this issue (as mentioned in the other issue made) #6

**Comment by aaron777collins** [comment]
To be specific, my latest changes detect if your install is broken and automatically fix it for you. I hope this helps! Please note that it will clear out your networks as a side-effect though.
